BEGIN
  EXECUTE IMMEDIATE 'DROP VIEW v_leaderboard';
EXCEPTION
  WHEN OTHERS THEN
    IF SQLCODE != -942 THEN RAISE; END IF;
END;
/

BEGIN
  EXECUTE IMMEDIATE 'DROP TABLE player_effects CASCADE CONSTRAINTS';
EXCEPTION WHEN OTHERS THEN IF SQLCODE != -942 THEN RAISE; END IF;
END;
/
BEGIN
  EXECUTE IMMEDIATE 'DROP TABLE trick_or_treat_actions CASCADE CONSTRAINTS';
EXCEPTION WHEN OTHERS THEN IF SQLCODE != -942 THEN RAISE; END IF;
END;
/
BEGIN
  EXECUTE IMMEDIATE 'DROP TABLE active_zombies CASCADE CONSTRAINTS';
EXCEPTION WHEN OTHERS THEN IF SQLCODE != -942 THEN RAISE; END IF;
END;
/
BEGIN
  EXECUTE IMMEDIATE 'DROP TABLE placed_towers CASCADE CONSTRAINTS';
EXCEPTION WHEN OTHERS THEN IF SQLCODE != -942 THEN RAISE; END IF;
END;
/
BEGIN
  EXECUTE IMMEDIATE 'DROP TABLE wave_progress CASCADE CONSTRAINTS';
EXCEPTION WHEN OTHERS THEN IF SQLCODE != -942 THEN RAISE; END IF;
END;
/
BEGIN
  EXECUTE IMMEDIATE 'DROP TABLE game_results CASCADE CONSTRAINTS';
EXCEPTION WHEN OTHERS THEN IF SQLCODE != -942 THEN RAISE; END IF;
END;
/
BEGIN
  EXECUTE IMMEDIATE 'DROP TABLE game_sessions CASCADE CONSTRAINTS';
EXCEPTION WHEN OTHERS THEN IF SQLCODE != -942 THEN RAISE; END IF;
END;
/
BEGIN
  EXECUTE IMMEDIATE 'DROP TABLE wave_composition CASCADE CONSTRAINTS';
EXCEPTION WHEN OTHERS THEN IF SQLCODE != -942 THEN RAISE; END IF;
END;
/
BEGIN
  EXECUTE IMMEDIATE 'DROP TABLE waves CASCADE CONSTRAINTS';
EXCEPTION WHEN OTHERS THEN IF SQLCODE != -942 THEN RAISE; END IF;
END;
/
BEGIN
  EXECUTE IMMEDIATE 'DROP TABLE tower_types CASCADE CONSTRAINTS';
EXCEPTION WHEN OTHERS THEN IF SQLCODE != -942 THEN RAISE; END IF;
END;
/
BEGIN
  EXECUTE IMMEDIATE 'DROP TABLE zombie_types CASCADE CONSTRAINTS';
EXCEPTION WHEN OTHERS THEN IF SQLCODE != -942 THEN RAISE; END IF;
END;
/
BEGIN
  EXECUTE IMMEDIATE 'DROP TABLE build_points CASCADE CONSTRAINTS';
EXCEPTION WHEN OTHERS THEN IF SQLCODE != -942 THEN RAISE; END IF;
END;
/
BEGIN
  EXECUTE IMMEDIATE 'DROP TABLE map_route CASCADE CONSTRAINTS';
EXCEPTION WHEN OTHERS THEN IF SQLCODE != -942 THEN RAISE; END IF;
END;
/
BEGIN
  EXECUTE IMMEDIATE 'DROP TABLE maps CASCADE CONSTRAINTS';
EXCEPTION WHEN OTHERS THEN IF SQLCODE != -942 THEN RAISE; END IF;
END;
/
BEGIN
  EXECUTE IMMEDIATE 'DROP TABLE players CASCADE CONSTRAINTS';
EXCEPTION WHEN OTHERS THEN IF SQLCODE != -942 THEN RAISE; END IF;
END;
/

CREATE TABLE players (
  player_id       NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY,
  player_name     VARCHAR2(100 CHAR) NOT NULL,
  password_hash   VARCHAR2(255) NOT NULL,
  registered_at   DATE DEFAULT SYSDATE NOT NULL,
  CONSTRAINT pk_players PRIMARY KEY (player_id),
  CONSTRAINT uq_players_name UNIQUE (player_name),
  CONSTRAINT ck_players_name_not_blank CHECK (TRIM(player_name) IS NOT NULL)
);

CREATE TABLE trick_or_treat_actions (
  action_id         NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY,
  player_id         NUMBER NOT NULL,
  target_player_id  NUMBER NOT NULL,
  action_type       VARCHAR2(20) NOT NULL,
  backfired         NUMBER(1) DEFAULT 0 NOT NULL,
  created_at        DATE DEFAULT SYSDATE NOT NULL,
  CONSTRAINT pk_treat_actions PRIMARY KEY (action_id),
  CONSTRAINT fk_treat_player FOREIGN KEY (player_id) REFERENCES players(player_id),
  CONSTRAINT fk_treat_target FOREIGN KEY (target_player_id) REFERENCES players(player_id),
  CONSTRAINT ck_treat_action CHECK (action_type IN ('SWEET', 'TRICK')),
  CONSTRAINT ck_treat_backfire CHECK (backfired IN (0, 1))
);

CREATE UNIQUE INDEX uq_treat_daily ON trick_or_treat_actions(player_id, action_type, TRUNC(created_at));

CREATE TABLE player_effects (
  effect_id         NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY,
  action_id         NUMBER NOT NULL,
  source_player_id  NUMBER NOT NULL,
  target_player_id  NUMBER NOT NULL,
  effect_type       VARCHAR2(30) NOT NULL,
  effect_value      NUMBER(8,2) NOT NULL,
  starts_at         DATE DEFAULT SYSDATE NOT NULL,
  expires_at        DATE NOT NULL,
  is_backfire       NUMBER(1) DEFAULT 0 NOT NULL,
  CONSTRAINT pk_player_effects PRIMARY KEY (effect_id),
  CONSTRAINT fk_effect_action FOREIGN KEY (action_id) REFERENCES trick_or_treat_actions(action_id) ON DELETE CASCADE,
  CONSTRAINT fk_effect_source FOREIGN KEY (source_player_id) REFERENCES players(player_id),
  CONSTRAINT fk_effect_target FOREIGN KEY (target_player_id) REFERENCES players(player_id),
  CONSTRAINT ck_effect_type CHECK (effect_type IN ('MONEY_BONUS', 'ZOMBIE_SPEED')),
  CONSTRAINT ck_effect_value CHECK (effect_value > 0),
  CONSTRAINT ck_effect_period CHECK (expires_at > starts_at),
  CONSTRAINT ck_effect_backfire CHECK (is_backfire IN (0, 1))
);

CREATE INDEX ix_player_effects_active ON player_effects(target_player_id, expires_at, effect_type);

CREATE TABLE maps (
  map_id             NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY,
  map_name           VARCHAR2(100 CHAR) NOT NULL,
  map_width          NUMBER(4) NOT NULL,
  map_height         NUMBER(4) NOT NULL,
  start_money        NUMBER(8) NOT NULL,
  start_base_health  NUMBER(8) NOT NULL,
  difficulty         VARCHAR2(20) DEFAULT 'normal' NOT NULL,
  CONSTRAINT pk_maps PRIMARY KEY (map_id),
  CONSTRAINT uq_maps_name UNIQUE (map_name),
  CONSTRAINT ck_maps_size CHECK (map_width > 0 AND map_height > 0),
  CONSTRAINT ck_maps_start_values CHECK (start_money >= 0 AND start_base_health > 0)
);

CREATE TABLE map_route (
  route_point_id  NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY,
  map_id          NUMBER NOT NULL,
  point_order     NUMBER(6) NOT NULL,
  x               NUMBER(4) NOT NULL,
  y               NUMBER(4) NOT NULL,
  CONSTRAINT pk_map_route PRIMARY KEY (route_point_id),
  CONSTRAINT fk_route_map FOREIGN KEY (map_id) REFERENCES maps(map_id) ON DELETE CASCADE,
  CONSTRAINT uq_route_order UNIQUE (map_id, point_order),
  CONSTRAINT uq_route_cell UNIQUE (map_id, x, y)
);

CREATE TABLE build_points (
  build_point_id  NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY,
  map_id          NUMBER NOT NULL,
  x               NUMBER(4) NOT NULL,
  y               NUMBER(4) NOT NULL,
  CONSTRAINT pk_build_points PRIMARY KEY (build_point_id),
  CONSTRAINT fk_build_map FOREIGN KEY (map_id) REFERENCES maps(map_id) ON DELETE CASCADE,
  CONSTRAINT uq_build_cell UNIQUE (map_id, x, y)
);

CREATE TABLE zombie_types (
  zombie_type_id    NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY,
  zombie_type_name  VARCHAR2(100 CHAR) NOT NULL,
  base_health       NUMBER(8) NOT NULL,
  base_speed        NUMBER(6,2) NOT NULL,
  armor             NUMBER(8) DEFAULT 0 NOT NULL,
  reward            NUMBER(8) NOT NULL,
  CONSTRAINT pk_zombie_types PRIMARY KEY (zombie_type_id),
  CONSTRAINT uq_zombie_type_name UNIQUE (zombie_type_name),
  CONSTRAINT ck_zombie_stats CHECK (base_health > 0 AND base_speed > 0 AND armor >= 0 AND reward >= 0)
);

CREATE TABLE tower_types (
  tower_type_id  NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY,
  tower_code     VARCHAR2(20) NOT NULL,
  tower_name     VARCHAR2(100 CHAR) NOT NULL,
  level_no       NUMBER(1) NOT NULL,
  damage         NUMBER(8) NOT NULL,
  range_cells    NUMBER(8) NOT NULL,
  fire_rate      NUMBER(6,2) NOT NULL,
  cost           NUMBER(8) NOT NULL,
  splash_radius  NUMBER(8) DEFAULT 0 NOT NULL,
  slow_percent   NUMBER(5,2) DEFAULT 0 NOT NULL,
  slow_duration  NUMBER(6,2) DEFAULT 0 NOT NULL,
  CONSTRAINT pk_tower_types PRIMARY KEY (tower_type_id),
  CONSTRAINT uq_tower_name UNIQUE (tower_name),
  CONSTRAINT uq_tower_level UNIQUE (tower_code, level_no),
  CONSTRAINT ck_tower_level CHECK (level_no BETWEEN 1 AND 3),
  CONSTRAINT ck_tower_stats CHECK (
    damage > 0
    AND range_cells > 0
    AND fire_rate > 0
    AND cost >= 0
    AND splash_radius >= 0
    AND slow_percent >= 0
    AND slow_percent < 1
    AND slow_duration >= 0
  )
);

CREATE TABLE waves (
  wave_id      NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY,
  map_id       NUMBER NOT NULL,
  wave_number  NUMBER(4) NOT NULL,
  CONSTRAINT pk_waves PRIMARY KEY (wave_id),
  CONSTRAINT fk_waves_map FOREIGN KEY (map_id) REFERENCES maps(map_id) ON DELETE CASCADE,
  CONSTRAINT uq_wave_number UNIQUE (map_id, wave_number),
  CONSTRAINT ck_wave_number CHECK (wave_number > 0)
);

CREATE TABLE wave_composition (
  wave_item_id        NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY,
  wave_id             NUMBER NOT NULL,
  zombie_type_id      NUMBER NOT NULL,
  zombie_count        NUMBER(6) NOT NULL,
  spawn_interval      NUMBER(6,2) NOT NULL,
  initial_delay       NUMBER(6,2) DEFAULT 0 NOT NULL,
  CONSTRAINT pk_wave_composition PRIMARY KEY (wave_item_id),
  CONSTRAINT fk_wave_item_wave FOREIGN KEY (wave_id) REFERENCES waves(wave_id) ON DELETE CASCADE,
  CONSTRAINT fk_wave_item_zombie FOREIGN KEY (zombie_type_id) REFERENCES zombie_types(zombie_type_id),
  CONSTRAINT ck_wave_item_values CHECK (zombie_count > 0 AND spawn_interval > 0 AND initial_delay >= 0)
);

CREATE TABLE game_sessions (
  session_id       NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY,
  player_id        NUMBER NOT NULL,
  player_name      VARCHAR2(100 CHAR) NOT NULL,
  map_id           NUMBER NOT NULL,
  money            NUMBER(8) NOT NULL,
  base_health      NUMBER(8) NOT NULL,
  current_wave     NUMBER(4) DEFAULT 1 NOT NULL,
  killed_zombies   NUMBER(8) DEFAULT 0 NOT NULL,
  simulation_time  NUMBER(10,2) DEFAULT 0 NOT NULL,
  status           VARCHAR2(20) DEFAULT 'running' NOT NULL,
  created_at       DATE DEFAULT SYSDATE NOT NULL,
  CONSTRAINT pk_game_sessions PRIMARY KEY (session_id),
  CONSTRAINT fk_session_player FOREIGN KEY (player_id) REFERENCES players(player_id),
  CONSTRAINT fk_session_map FOREIGN KEY (map_id) REFERENCES maps(map_id),
  CONSTRAINT ck_session_money CHECK (money >= 0),
  CONSTRAINT ck_session_health CHECK (base_health >= 0),
  CONSTRAINT ck_session_kills CHECK (killed_zombies >= 0),
  CONSTRAINT ck_session_status CHECK (status IN ('running', 'win', 'lose'))
);

CREATE INDEX ix_sessions_player_status ON game_sessions(player_id, status);

CREATE TABLE wave_progress (
  wave_progress_id  NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY,
  session_id        NUMBER NOT NULL,
  wave_id           NUMBER NOT NULL,
  wave_item_id      NUMBER NOT NULL,
  released_count    NUMBER(6) DEFAULT 0 NOT NULL,
  next_spawn_time   NUMBER(10,2) NOT NULL,
  CONSTRAINT pk_wave_progress PRIMARY KEY (wave_progress_id),
  CONSTRAINT fk_progress_session FOREIGN KEY (session_id) REFERENCES game_sessions(session_id) ON DELETE CASCADE,
  CONSTRAINT fk_progress_wave FOREIGN KEY (wave_id) REFERENCES waves(wave_id),
  CONSTRAINT fk_progress_wave_item FOREIGN KEY (wave_item_id) REFERENCES wave_composition(wave_item_id),
  CONSTRAINT uq_progress_item UNIQUE (session_id, wave_item_id),
  CONSTRAINT ck_progress_values CHECK (released_count >= 0 AND next_spawn_time >= 0)
);

CREATE TABLE placed_towers (
  placed_tower_id      NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY,
  session_id           NUMBER NOT NULL,
  tower_type_id        NUMBER NOT NULL,
  remaining_cooldown   NUMBER(8,2) DEFAULT 0 NOT NULL,
  build_point_id       NUMBER NOT NULL,
  CONSTRAINT pk_placed_towers PRIMARY KEY (placed_tower_id),
  CONSTRAINT fk_placed_session FOREIGN KEY (session_id) REFERENCES game_sessions(session_id) ON DELETE CASCADE,
  CONSTRAINT fk_placed_tower_type FOREIGN KEY (tower_type_id) REFERENCES tower_types(tower_type_id),
  CONSTRAINT fk_placed_build_point FOREIGN KEY (build_point_id) REFERENCES build_points(build_point_id),
  CONSTRAINT uq_placed_tower_cell UNIQUE (session_id, build_point_id),
  CONSTRAINT ck_placed_cooldown CHECK (remaining_cooldown >= 0)
);

CREATE TABLE active_zombies (
  active_zombie_id     NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY,
  wave_progress_id     NUMBER NOT NULL,
  zombie_type_id       NUMBER NOT NULL,
  current_health       NUMBER(8) NOT NULL,
  max_health           NUMBER(8) DEFAULT 0 NOT NULL,
  armor_multiplier     NUMBER(6,2) DEFAULT 1 NOT NULL,
  route_point_id       NUMBER NOT NULL,
  segment_progress     NUMBER(8,4) DEFAULT 0 NOT NULL,
  status               VARCHAR2(20) DEFAULT 'active' NOT NULL,
  slow_until           NUMBER(10,2) DEFAULT 0 NOT NULL,
  speed_multiplier     NUMBER(4,2) DEFAULT 1 NOT NULL,
  CONSTRAINT pk_active_zombies PRIMARY KEY (active_zombie_id),
  CONSTRAINT fk_active_progress FOREIGN KEY (wave_progress_id) REFERENCES wave_progress(wave_progress_id) ON DELETE CASCADE,
  CONSTRAINT fk_active_zombie_type FOREIGN KEY (zombie_type_id) REFERENCES zombie_types(zombie_type_id),
  CONSTRAINT fk_active_route_point FOREIGN KEY (route_point_id) REFERENCES map_route(route_point_id),
  CONSTRAINT ck_active_status CHECK (status IN ('active', 'inactive')),
  CONSTRAINT ck_active_health CHECK (current_health >= 0 AND max_health >= 0 AND armor_multiplier >= 1),
  CONSTRAINT ck_active_progress CHECK (segment_progress >= 0 AND segment_progress < 1),
  CONSTRAINT ck_active_slow CHECK (slow_until >= 0 AND speed_multiplier > 0 AND speed_multiplier <= 1)
);

CREATE INDEX ix_active_zombies_progress ON active_zombies(wave_progress_id, status);

CREATE TABLE game_results (
  result_id        NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY,
  session_id       NUMBER NOT NULL,
  player_id        NUMBER NOT NULL,
  player_name      VARCHAR2(100 CHAR) NOT NULL,
  map_id           NUMBER NOT NULL,
  result_status    VARCHAR2(10) NOT NULL,
  reached_wave     NUMBER(4) NOT NULL,
  duration         NUMBER(10,2) NOT NULL,
  finished_at      DATE DEFAULT SYSDATE NOT NULL,
  CONSTRAINT pk_game_results PRIMARY KEY (result_id),
  CONSTRAINT uq_result_session UNIQUE (session_id),
  CONSTRAINT fk_result_session FOREIGN KEY (session_id) REFERENCES game_sessions(session_id),
  CONSTRAINT fk_result_player FOREIGN KEY (player_id) REFERENCES players(player_id),
  CONSTRAINT fk_result_map FOREIGN KEY (map_id) REFERENCES maps(map_id),
  CONSTRAINT ck_result_status CHECK (result_status IN ('win', 'lose')),
  CONSTRAINT ck_result_values CHECK (reached_wave > 0 AND duration >= 0)
);

CREATE OR REPLACE VIEW v_leaderboard AS
SELECT
  r.map_id,
  m.map_name,
  r.player_name,
  r.result_status,
  r.reached_wave,
  r.duration,
  r.finished_at,
  ROW_NUMBER() OVER (
    PARTITION BY r.map_id
    ORDER BY
      CASE r.result_status WHEN 'win' THEN 0 ELSE 1 END,
      r.reached_wave DESC,
      r.duration ASC,
      r.finished_at DESC
  ) AS place_no
FROM game_results r
JOIN maps m ON m.map_id = r.map_id;

COMMENT ON TABLE players IS 'Игроки: имя, хэш пароля и дата регистрации.';
COMMENT ON TABLE trick_or_treat_actions IS 'Журнал ежедневных выборов Сладость или гадость.';
COMMENT ON TABLE player_effects IS 'Временные эффекты игроков: бонус монет или ускорение зомби.';
COMMENT ON TABLE maps IS 'Карты Tower Defense: размер поля, стартовые деньги и здоровье базы.';
COMMENT ON TABLE map_route IS 'Клетки маршрута, по которому движутся зомби.';
COMMENT ON TABLE build_points IS 'Разрешенные клетки для установки башен.';
COMMENT ON TABLE zombie_types IS 'Справочник типов зомби: здоровье, скорость, броня, награда.';
COMMENT ON TABLE tower_types IS 'Справочник башен; каждый уровень улучшения хранится отдельной записью.';
COMMENT ON TABLE waves IS 'Волны врагов для каждой карты.';
COMMENT ON TABLE wave_composition IS 'Пачки спавна внутри волн.';
COMMENT ON TABLE game_sessions IS 'Активные и завершенные игровые сессии.';
COMMENT ON TABLE wave_progress IS 'Прогресс выпуска врагов по каждой пачке волны.';
COMMENT ON TABLE placed_towers IS 'Башни, установленные в рамках конкретной сессии.';
COMMENT ON TABLE active_zombies IS 'Текущее состояние врагов в рамках сессии.';
COMMENT ON TABLE game_results IS 'Архив результатов завершенных партий.';
